### ISSUE TITLE
Can't evaluate source file with underscore in name

### ISSUE THREAD

**Issue by psybers** [boalang/compiler#109]
If you try to evaluate a file with an underscore in the name, it fails:

````
dhcp-129-1-64-201:compiler-master rdyer$ ./evaluate.sh catA_p1.boa out
17/03/20 11:19:58 INFO compiler.BoaCompiler: catA_p1.boa: task complexity: simple
17/03/20 11:19:58 INFO compiler.BoaCompiler: compiling: ./compile/boa/CatA_P1.java
17/03/20 11:19:58 INFO compiler.BoaCompiler: classpath: .:./dist/boa-compiler.jar:./lib/antlr-4.5-complete.jar:./lib/checkstyle-6.19-all.jar:./lib/com.jcraft.jsch-all-1.0.1.release.jar:./lib/commons-cli-1.2.jar:./lib/commons-lang-2.4.jar:./lib/commons-math-2.1.jar:./lib/hadoop-core-1.0.4.jar:./lib/junit-4.11.jar:./lib/mockito-all-1.8.5.jar:./lib/mrunit-0.9.0-incubating-hadoop1.jar:./lib/evaluator/com.springsource.org.codehaus.jackson-1.4.2.jar:./lib/evaluator/com.springsource.org.codehaus.jackson.mapper-1.4.2.jar:./lib/evaluator/commons-configuration-1.6.jar:./lib/evaluator/commons-httpclient-3.1.0.redhat-7.jar:./lib/evaluator/commons-io-2.4.jar:./lib/evaluator/jackson-mapper-asl-1.9.13.jar:./lib/datagen/commons-beanutils-1.8.3.jar:./lib/datagen/commons-collections-3.2.1.jar:./lib/datagen/commons-configuration-1.6.jar:./lib/datagen/commons-io-2.4.jar:./lib/datagen/commons-logging-1.1.1.jar:./lib/datagen/ezmorph-1.0.6.jar:./lib/datagen/jena-core-2.7.3.jar:./lib/datagen/jena-iri-0.9.3.jar:./lib/datagen/json-lib-2.4-jdk15.jar:./lib/datagen/log4j-1.2.16.jar:./lib/datagen/org.eclipse.core.contenttype_3.4.100.dist.jar:./lib/datagen/org.eclipse.core.jobs_3.5.101.dist.jar:./lib/datagen/org.eclipse.core.resources_3.7.101.dist.jar:./lib/datagen/org.eclipse.core.runtime_3.7.0.dist.jar:./lib/datagen/org.eclipse.equinox.common_3.6.0.dist.jar:./lib/datagen/org.eclipse.equinox.preferences_3.4.2.dist.jar:./lib/datagen/org.eclipse.equinox.registry.source_3.5.100.v20110502.jar:./lib/datagen/org.eclipse.equinox.registry_3.5.100.v20110502.jar:./lib/datagen/org.eclipse.jdt.core_3.11.0.v20150602-1242.jar:./lib/datagen/org.eclipse.jgit_4.0.1.201506240215-r.jar:./lib/datagen/org.eclipse.osgi_3.7.2.dist.jar:./lib/datagen/org.eclipse.wst.jsdt.core_1.3.1.v201401291437.jar:./lib/datagen/protobuf-java-2.5.0.jar:./lib/datagen/slf4j-api-1.4.3.jar:./lib/datagen/slf4j-log4j12-1.4.3.jar:./lib/datagen/svnkit-1.7.6.jar:./lib/datagen/xercesImpl.jar:./lib/datagen/xml-apis.jar:./lib/datagen/xml-security-impl-1.0.jar:./compile
warning: [options] bootstrap class path not set in conjunction with -source 1.5
Note: ./compile/boa/CatA_P1.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
java.lang.NoClassDefFoundError: boa/CatA_p1 (wrong name: boa/CatA_P1)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at boa.evaluator.BoaEvaluator.evaluate(BoaEvaluator.java:76)
	at boa.evaluator.BoaEvaluator.main(BoaEvaluator.java:110)
	at boa.BoaMain.main(BoaMain.java:54)
Total Time Taken: 2976
Exception in thread "main" java.lang.NullPointerException
	at boa.evaluator.BoaEvaluator.getResults(BoaEvaluator.java:139)
	at boa.evaluator.BoaEvaluator.main(BoaEvaluator.java:113)
	at boa.BoaMain.main(BoaMain.java:54)
````

But you *can* run compile.sh on the same file and it works.

**Comment by psybers** [comment]
Similar problem for a dash in the name.
