### ISSUE TITLE
Hadoop not able to set permissions to temporary directories on Windows

### ISSUE THREAD

**Issue by arafat1** [boalang/compiler#110]
On Windows, if evaluate.bat is used, hadoop is not able to set permissions to create temporary directories as shown below:

````
 ERROR security.UserGroupInformation: PriviledgedActionException as:Mohd cause:java.io.IOException: Failed to set permissions of path: \tmp\hadoop-Mohd\mapred\staging\Mohd1052813401\.staging to 0700
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at boa.evaluator.BoaEvaluator.evaluate(BoaEvaluator.java:78)
        at boa.evaluator.BoaEvaluator.main(BoaEvaluator.java:110)
        at boa.BoaMain.main(BoaMain.java:54)
Caused by: java.io.IOException: Failed to set permissions of path: \tmp\hadoop-Mohd\mapred\staging\Mohd1052813401\.staging to 0700
        at org.apache.hadoop.fs.FileUtil.checkReturnValue(FileUtil.java:689)
        at org.apache.hadoop.fs.FileUtil.setPermission(FileUtil.java:662)
        at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:509)
        at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:344)
        at org.apache.hadoop.fs.FilterFileSystem.mkdirs(FilterFileSystem.java:189)
        at org.apache.hadoop.mapreduce.JobSubmissionFiles.getStagingDir(JobSubmissionFiles.java:116)
        at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:856)
        at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:850)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1121)
        at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:850)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:500)
        at boa.SourceFile.run(SourceFile.java:82)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
        at boa.SourceFile.main(SourceFile.java:30)
        ... 7 more
Total Time Taken: 3497
Exception in thread "main" java.lang.NullPointerException
        at boa.evaluator.BoaEvaluator.getResults(BoaEvaluator.java:139)
        at boa.evaluator.BoaEvaluator.main(BoaEvaluator.java:113)
        at boa.BoaMain.main(BoaMain.java:54)
````

**Comment by psybers** [comment]
Known upstream bug: https://issues.apache.org/jira/browse/HADOOP-7682

**Comment by psybers** [comment]
Possible workaround: https://github.com/congainc/patch-hadoop_7682-1.0.x-win

**Comment by psybers** [comment]
Used the fix suggested here: https://issues.apache.org/jira/browse/HADOOP-7682?focusedCommentId=13648585&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13648585
