### ISSUE TITLE
Project protobuf message is too large causing integer overflow when reading

### ISSUE THREAD

**Issue by nguyenhoan** [boalang/compiler#177]
projects-0-1523660480203.seq
```
java.lang.NegativeArraySizeException
        at org.apache.hadoop.io.BytesWritable.setCapacity(BytesWritable.java:119)
        at org.apache.hadoop.io.BytesWritable.setSize(BytesWritable.java:98)
        at org.apache.hadoop.io.BytesWritable.readFields(BytesWritable.java:153)
        at org.apache.hadoop.io.SequenceFile$Reader.getCurrentValue(SequenceFile.java:1809)
        at org.apache.hadoop.io.SequenceFile$Reader.next(SequenceFile.java:1937)
        at boa.datagen.SeqCombiner.main(SeqCombiner.java:71)
        at boa.datagen.BoaGenerator.main(BoaGenerator.java:66)
```
https://github.com/boalang/compiler/blob/datagen2017/src/java/boa/datagen/SeqCombiner.java#L71

**Comment by nguyenhoan** [comment]
@psybers should commits be stored in a separate sequence file similarly to asts?
